version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sn_db
    ports:
      - "5432:5432"
    volumes:
      - sn_db_data:/var/lib/postgresql/data
volumes:
  sn_db_data: